# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # This is required for trusted publishing

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build wheels with cibuildwheel
        uses: pypa/cibuildwheel@v2.18.0
        env:
          CIBW_ARCHS: auto
          CIBW_BUILD: cp38-* cp39-* cp310-* cp311-* cp312-* cp313-*
          # Install build dependencies like numpy and pybind11 before the build process starts.
          CIBW_BEFORE_BUILD: pip install numpy pybind11

      - name: Publish distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheelhouse/
